/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.awt.image.ImageObserver;
import java.util.function.Predicate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DepositMenu extends javax.swing.JDialog {
    
    private Customer customer = null;
    Bank bank;
    
    public DepositMenu(java.awt.Frame parent, boolean modal, Bank bank,Customer customer ) {
        super(parent, modal);        
        this.customer = customer;
        setLocationRelativeTo(parent);
        this.bank = bank;
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountTable = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deposit Menu");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        amountTable.setText("Deposit Amount");
        getContentPane().add(amountTable);
        getContentPane().add(amountField);

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositButton);

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       this.dispose();  
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        /*Verify the deposit is not empty
          Verify that deposit is not negative number
          Verify that a field is chosen
          Make the deposit  
        */
        StringBuilder warnings = new StringBuilder();                        
                             
        if(!amountField.getText().isEmpty() && !amountField.getText().contains("-"))
        {
           double amount = Double.parseDouble(amountField.getText());          
           int result = JOptionPane.showConfirmDialog(this,"Deposit $"+ amount +
                   "to the account ?\nInterest earned: $" + bank.checkInterest(
                           customer.getAccount().getBalance(), amount) * 100);           
           
           if(result == JOptionPane.OK_OPTION){
               try {
                   bank.deposit(customer.getAccount().getAccountNumber(), amount);           
               } catch (InvalidAmountException ex) {
                   Logger.getLogger(DepositMenu.class.getName()).log(Level.SEVERE, null, ex);
               }
              this.dispose();    
           }
        }
         else{
            JOptionPane.showMessageDialog(this,"Deposit must be positive a number." ,"Warning!",
                      JOptionPane.WARNING_MESSAGE);
        }
   
    }//GEN-LAST:event_depositButtonActionPerformed
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton depositButton;
    // End of variables declaration//GEN-END:variables
    
}
