/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.awt.image.ImageObserver;
import java.util.function.Predicate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class WithdrawMenu extends javax.swing.JDialog {
    
    private Customer customer = null;
    private Bank bank;
    
    public WithdrawMenu(java.awt.Frame parent, boolean modal, Customer customer, Bank bank ) {
        super(parent, modal);        
        this.customer = customer;
        setLocationRelativeTo(parent);
        initComponents();
        this.bank = bank;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountTable = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        withDrawalButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deposit Menu");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        amountTable.setText("Withdrawal amount");
        getContentPane().add(amountTable);
        getContentPane().add(amountField);

        withDrawalButton.setText("Withdrawal");
        withDrawalButton.setName("withdrawalButton"); // NOI18N
        withDrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withDrawalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withDrawalButton);

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       this.dispose();  
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void withDrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withDrawalButtonActionPerformed
                                     
        if(!amountField.getText().isEmpty() && !amountField.getText().contains("-"))
        {
           int amount = Integer.parseInt(amountField.getText());
           int result = JOptionPane.showConfirmDialog(this,"Withdraw $"+ amount +
                   "from the account ?\nTransaction fee: $" + bank.getTransactionFee
                      (customer.getAccount().getAccountType()));
           
           if(result == JOptionPane.OK_OPTION){
               
               try {
                   bank.withdraw(customer.getAccount().getAccountNumber(), amount);                  
               } catch (InsufficientFundsException ex) {
                   Logger.getLogger(WithdrawMenu.class.getName()).log(Level.SEVERE, null, ex);
               }                                 
               
              this.dispose();    
           }
        }
         else{
            JOptionPane.showMessageDialog(this,"Withdrawal amount must be a number." ,"Warning!",
                      JOptionPane.WARNING_MESSAGE);
        }
   
    }//GEN-LAST:event_withDrawalButtonActionPerformed
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton withDrawalButton;
    // End of variables declaration//GEN-END:variables
    
}
